version: '3.7'

services:
  db:
    image: postgres:14
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d $${POSTGRES_DB} -U $${POSTGRES_USER}"]
      start_period: 10s
      interval: 10s
      retries: 5
      timeout: 5s
  api:
    build:
      context: /
      dockerfile: Dockerfile
    environment:
      DB_URL: jdbc:postgresql://db:5432/postgres
      DB_USER: postgres
      DB_PASS: postgres
    ports:
        - "8080:8080"
    depends_on:
      db:
        condition: service_healthy
